- Topics Studied:
    - How to Improve Training Pipeline:
        - NN Module 
        - torch.optim module
    - What are the improvements:
        - not give parameters manually
        - used built in loss function
        - used built in activation function
        - not update parameter manually will use torch.optim
    - Summary:
        - Built an nueral network using nn module
        - Use built in activation function
        - Use built in loss function
        - Use built in optimizer

- The nn module:
    - nn module is an liabrary of pytorch that provide wide range of classes and functions designed to help developer to build neural network efficiently and effectively.
    - It abstracts the complexity of creating and training neural network by offering pre-built layers, loss functions, activation functions and other utilities.

- Key Components of torch.nn:
1) Modules(Layers):
    - nn.Module : The base class for all nueral network modules. Your custom models and layers should subclass this class.
    - Common Layers : Include layers like nn.Linear (fully connected layer), nn.Conv2D (convolutional layer), nn.LSTM (reccurent layer) and many others.

2) Activation Functions:
    - Functions like nn.ReLU, nn.Sigmoid and nn.Tanh itroduce non-linearities to the model, allowing it to learn complex patterns.

3) Loss Functions:
    - Provide loss functions such as nn.CrossEntropyLoss, nn,MSELoss and nn.NLLLoss to quanify the differnce between the model's predictions and the actual targets/

4) Container Modules:
    - nn.Sequential : A sequential container to stack layers in orders.

5) Regularization and Dropout:
    - Layer like nn.Dropout and nn.BatchNorm1d help prevent overfitting and improves the model's ability to generalize new data. 

In [6]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [7]:
# create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

# call model and forward pass
model(features)


tensor([[0.4489],
        [0.4987],
        [0.5046],
        [0.4673],
        [0.5005],
        [0.5077],
        [0.4622],
        [0.4915],
        [0.4294],
        [0.4860]], grad_fn=<SigmoidBackward0>)

In [8]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.2088, -0.0418, -0.1466, -0.3368, -0.1829]], requires_grad=True)

In [9]:
# show model bias
model.linear.bias

Parameter containing:
tensor([0.2119], requires_grad=True)

In [10]:
%pip install torchinfo

In [11]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [17]:
# create new nn
# input layer 5 nuerons 
# hidden layer 3 nuerons
# output layer 1 nueron (y_pred)

import torch
import torch.nn as nn

class New_Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out


In [18]:
# create dataset
features = torch.rand(10,5)

#create model
model = New_Model(features.shape[1])

# call model and forward pass
model(features)

tensor([[0.4553],
        [0.4528],
        [0.4136],
        [0.4135],
        [0.4044],
        [0.4145],
        [0.4635],
        [0.4163],
        [0.3954],
        [0.4679]], grad_fn=<SigmoidBackward0>)

In [20]:
print("linear 1 weight: ",model.linear1.weight,"\n")
print("linear 2 weights: ",model.linear2.weight,"\n")
print("linear 1 bias:",model.linear1.bias,"\n")
print("linear 2 bias: ",model.linear2.bias,"\n")

linear 1 weight:  Parameter containing:
tensor([[ 0.2605,  0.0496, -0.4300,  0.3551,  0.2622],
        [ 0.3513,  0.2764, -0.1769,  0.1811,  0.0302],
        [ 0.0909,  0.2776,  0.2496,  0.3849, -0.3991]], requires_grad=True) 

linear 2 weights:  Parameter containing:
tensor([[ 0.4668,  0.5760, -0.1879]], requires_grad=True) 

linear 1 bias: Parameter containing:
tensor([-0.4245,  0.1153,  0.0673], requires_grad=True) 

linear 2 bias:  Parameter containing:
tensor([-0.4448], requires_grad=True) 



In [21]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
New_Model                                [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [ ]:
df = pd.read_csv("breast_cancer_data.csv")
df.head()

In [ ]:
df.shape

In [ ]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [ ]:
df.head()

train test split

In [ ]:
x = df.drop(columns="diagnosis")
y = df["diagnosis"]
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

label encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

array to tensor

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

defining model

In [ ]:
class MySimpleNN():
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)
        
    def forward(self,X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred,y):
        # clamp prediction to avoide log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

        # calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor)* torch.log(1-y_pred)).mean()
        return loss


important parameters

In [ ]:
learning_rate = 0.1
epochs = 35

training pipeline

In [ ]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
    # forward pass
    y_pred = model.forward(X_train_tensor)
    
    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)

    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")