# <u>**Tensors**</u>

- What are Tensors?
    - Tensor is data strcture, it is specialized multi-dimensional array designed for mathematical and computational efficiency.
    - Dimesion in tensor is, how span of tensor in directions.

- Real World Examples of Tensors:
    1) Scaler : 0 Dimensional Tensor
        - Single Number
    2) Vector : 1 Dimensional Tensor
        - Sequence or collection (list of number)
    3) Metrices : 2 Dimensional Tensor
        - Represent Tabular or grid type data
    4) 3D Tensor : Coloured Image
        - RGB Image
    5) 4D Tensor : Batches of RGD image
        - Baches of RGB Image
    6) 5D Tensor : Video Data
        - Video Data

- Why are Tensors Useful?
    - Mathematical Operation
    - Real World Data
    - Efficient Computation

- Where are Tensors used in Deep Learning?
    - Data Storage
    - Weight and Biases
    - Metrix Operation
    - Training Process

In [2]:
import torch
print(torch.__version__)

2.10.0+cu128


In [3]:
if torch.cuda.is_available():
    print("GPU is availabel")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available using CPU")

GPU is availabel
Using GPU: Tesla T4


Creating Tensor

In [4]:
# using empty
a = torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.2050, 0.4563, 0.8888],
        [0.8742, 0.9610, 0.3415]])

In [9]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# other ways

# arange
print("using arange --->", torch.arange(0,10,2),"\n")

# using linspace
print("using linspace --->",torch.linspace(0,10,10),"\n")

# using eye
print("using eye --->",torch.eye(5),"\n")

# using full 
print("using full --->", torch.full((3,3),5),"\n")

using arange ---> tensor([0, 2, 4, 6, 8]) 

using linspace ---> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000]) 

using eye ---> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]) 

using full ---> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]) 



Tensor Shapes

In [12]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
x.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Tensor Data Types

In [18]:
# find data type
x.dtype

torch.int64

In [19]:
# assingn data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [20]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [21]:
# converting to anothe dtype
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


Mathematical Operations

1. Scaler operation

In [22]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [23]:
# addition
print(x+2)

# substraction
print(x-1)

# multiplication
print(x*100)

# division
print(x/10)

# int division
print(x//3)



tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[-0.2882, -0.2124],
        [-0.5817, -0.0986]])
tensor([[71.1765, 78.7581],
        [41.8305, 90.1415]])
tensor([[0.0712, 0.0788],
        [0.0418, 0.0901]])
tensor([[0., 0.],
        [0., 0.]])


2. Element Wise Operation

In [24]:
x = torch.rand(2,3)
y = torch.rand(2,3)

In [25]:
# add
print(x+y)

# sub
print(x-y)

# multi
print(x*y)

# divide
print(x/y)

# fd
print(x//y)

# pow
print(x**y)

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])
tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])
tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])
tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])
tensor([[1., 0., 0.],
        [0., 0., 1.]])
tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])


In [26]:
c = torch.tensor([1,2,3,-4])

In [27]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [28]:
# negative
torch.neg(c)

tensor([-1, -2, -3,  4])

In [29]:
d = torch.tensor([1.2,2.1,3.3,4.4,5.5])

In [30]:
# round
torch.round(d)

tensor([1., 2., 3., 4., 6.])

In [31]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5., 6.])

In [32]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4., 5.])

In [33]:
# clamp
torch.clamp(d,min=2, max=4)

tensor([2.0000, 2.1000, 3.3000, 4.0000, 4.0000])

3. Reduction Operation

In [34]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [35]:
# sum
print(torch.sum(e))

# sum along columns
print(torch.sum(e,dim=0))

# sum along rows
print(torch.sum(e,dim=1))

tensor(24.)
tensor([ 8.,  0., 16.])
tensor([15.,  9.])


In [36]:
# mean
print(torch.mean(e))

# mean along col
print(torch.mean(e,dim=0))

# mean along row
print(torch.mean(e,dim=1))

tensor(4.)
tensor([4., 0., 8.])
tensor([5., 3.])


In [37]:
# median
print(torch.median(e))

# median along col
print(torch.median(e,dim=0))

# median along row
print(torch.median(e,dim=1))

tensor(0.)
torch.return_types.median(
values=tensor([0., 0., 7.]),
indices=tensor([1, 0, 0]))
torch.return_types.median(
values=tensor([7., 0.]),
indices=tensor([2, 1]))


In [38]:
# max
print(torch.max(e))

# min
print(torch.min(e))

tensor(9.)
tensor(0.)


In [39]:
# prod
print(torch.prod(e))

tensor(0.)


In [40]:
# standard deviation
print(torch.std(e))

tensor(4.4272)


In [41]:
# variance
print(torch.var(e))

tensor(19.6000)


In [42]:
# argmax
print(torch.argmax(e))

tensor(5)


4. Matrix Operation

In [43]:
f = torch.randint(size=(2,3),low =0,high= 10)
g = torch.randint(size=(3,2),low =0,high= 10)
print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [44]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [45]:
vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,4])

# dot product
torch.dot(vec1,vec2)

tensor(11)

In [46]:
# transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [47]:
h = torch.randint(size=(3,3),low=1,high=10,dtype=torch.float32)
h

tensor([[5., 4., 7.],
        [2., 1., 1.],
        [4., 6., 6.]])

In [48]:
# determinant
torch.det(h)

tensor(24.0000)

In [49]:
# inverse
torch.inverse(h)

tensor([[-1.6557e-09,  7.5000e-01, -1.2500e-01],
        [-3.3333e-01,  8.3333e-02,  3.7500e-01],
        [ 3.3333e-01, -5.8333e-01, -1.2500e-01]])

5. Comparision operations

In [50]:
i = torch.randint(size=(2,3),low = 1, high = 10)
j = torch.randint(size=(2,3),low = 0, high = 9)
print(i)
print(j)

tensor([[6, 1, 4],
        [1, 3, 7]])
tensor([[1, 1, 7],
        [3, 0, 0]])


In [51]:
# greater than
print(i>j)

# less than
print(i<j)

# equal to
print(i == j)

# not eqaul to
print(i != j)

# greater than eqaul to
print(i>=j)

# less than eqaul to
print(i<=j)


tensor([[ True, False, False],
        [False,  True,  True]])
tensor([[False, False,  True],
        [ True, False, False]])
tensor([[False,  True, False],
        [False, False, False]])
tensor([[ True, False,  True],
        [ True,  True,  True]])
tensor([[ True,  True, False],
        [False,  True,  True]])
tensor([[False,  True,  True],
        [ True, False, False]])


6. Special Functions

In [52]:
x = torch.randint(size=(2,3),low=5 ,high=10,dtype=torch.float32)
x

tensor([[8., 8., 5.],
        [5., 6., 9.]])

In [53]:
# log
torch.log(x)

tensor([[2.0794, 2.0794, 1.6094],
        [1.6094, 1.7918, 2.1972]])

In [54]:
# exp
torch.exp(x)

tensor([[2980.9580, 2980.9580,  148.4132],
        [ 148.4132,  403.4288, 8103.0840]])

In [55]:
# sqrt
torch.sqrt(x)

tensor([[2.8284, 2.8284, 2.2361],
        [2.2361, 2.4495, 3.0000]])

In [56]:
# sigmoid
torch.sigmoid(x)

tensor([[0.9997, 0.9997, 0.9933],
        [0.9933, 0.9975, 0.9999]])

In [57]:
# softmax
torch.softmax(x,dim=0)

tensor([[0.9526, 0.8808, 0.0180],
        [0.0474, 0.1192, 0.9820]])

In [58]:
# relu
torch.relu(x)

tensor([[8., 8., 5.],
        [5., 6., 9.]])

Inplace Operations

In [59]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [60]:
m + n

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [61]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [62]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [63]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [64]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [65]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

Copying a Tensor

In [66]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [67]:
b = a

In [68]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [69]:
print(id(a) == id(b))

True


In [70]:
b = a.clone()

In [71]:
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [72]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [73]:
print(id(a) == id(b))

False


Tensor Operations on GPU

In [74]:
torch.cuda.is_available()

True

In [75]:
device = torch.device("cuda")
device

device(type='cuda')

In [76]:
# creating tensor on gpu
torch.rand(2,3,device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [77]:
# moving an existing tensors on GPU
a = torch.rand(2,3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [78]:
b = a.to(device)
b

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]], device='cuda:0')

In [79]:
b + 5

tensor([[5.2243, 5.8935, 5.0497],
        [5.1780, 5.3011, 5.1893]], device='cuda:0')

In [82]:
import time

# def the size pf the matrices
size = 10000

matrix_cpu1 = torch.rand(size,size)
matrix_cpu2 = torch.rand(size,size)

# measuring time on cpu
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# move on gpu
matrix_gpu1 = matrix_cpu1.to("cuda")
matrix_gpu2 = matrix_cpu2.to("cuda")

# measuring time on gpu
start_time = time.time()
result_cpu = torch.matmul(matrix_gpu1,matrix_gpu2)
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# compare result
print(cpu_time / gpu_time)

Time on CPU: 16.8935 seconds
Time on GPU: 0.0207 seconds
816.7060593137311


Reshaping Tensors

In [83]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [84]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [85]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [87]:
b = torch.rand(2,3,4)
b

tensor([[[0.1861, 0.7517, 0.7577, 0.2803],
         [0.8751, 0.4261, 0.9365, 0.5205],
         [0.1217, 0.5074, 0.7335, 0.7166]],

        [[0.4271, 0.8363, 0.6585, 0.7211],
         [0.7063, 0.0397, 0.0140, 0.8291],
         [0.4812, 0.9135, 0.3784, 0.3297]]])

In [90]:
# permute
b.permute(2,0,1)

tensor([[[0.1861, 0.8751, 0.1217],
         [0.4271, 0.7063, 0.4812]],

        [[0.7517, 0.4261, 0.5074],
         [0.8363, 0.0397, 0.9135]],

        [[0.7577, 0.9365, 0.7335],
         [0.6585, 0.0140, 0.3784]],

        [[0.2803, 0.5205, 0.7166],
         [0.7211, 0.8291, 0.3297]]])

In [92]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [97]:
# unsqueeze
# image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [99]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

NumPy and PyTorch

In [100]:
import numpy as np

In [101]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [102]:
b = a.numpy()
b

array([1, 2, 3])

In [103]:
type(b)

numpy.ndarray

In [104]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [106]:
d = torch.from_numpy(c)
d

tensor([1, 2, 3])