In [15]:
"""
Task 1

Create tensors using:

empty
zeros
ones
rand
tensor
arange
linspace

without looking at notes.
"""
import torch

empty_tensor = torch.empty((0))
print("empty tensor",empty_tensor,"checking datatype", type(empty_tensor))

zeros_tensor = torch.zeros(4,4)
print("zeros tensor\n",zeros_tensor)

ones_tensor = torch.ones((3,3))
print("ones tensor \n", ones_tensor)

rand_tensor = torch.rand(6,2)
print("rand tensor \n",rand_tensor)

arange_tensor = torch.arange(5)
print("arange tensor\n", arange_tensor)

linspace_tensor = torch.linspace(-20,20,5)
print("linspace tensor\n", linspace_tensor)

empty tensor tensor([]) checking datatype <class 'torch.Tensor'>
zeros tensor
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
ones tensor 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
rand tensor 
 tensor([[0.6761, 0.5644],
        [0.2757, 0.4029],
        [0.7437, 0.8148],
        [0.1772, 0.9676],
        [0.6756, 0.4729],
        [0.7845, 0.3377]])
arange tensor
 tensor([0, 1, 2, 3, 4])
linspace tensor
 tensor([-20., -10.,   0.,  10.,  20.])
